### ISSUE TITLE
Tabula-java doesn't auto-detect tables when using -g on the command line

### ISSUE THREAD

**Issue by tanyaroosta** [tabulapdf/tabula-java#223]
I have a number of pdf files and am trying to automate the table extraction using the command line. I don't know ahead of time if/which pages in my pdf have a table, so I am using the -g option based on the documentation and this link: https://github.com/tabulapdf/tabula/issues/517

However, the -g option does not seem to work and the output includes all text and tables together.  
Any help is greatly appreciated.

**Comment by laigor** [comment]
It looks like tabula-1.0.2-jar-with-dependencies ignores the -d and -g keys. Automatic detection of tables is a very necessary function for tabula-java and I want to sponsor its refinement. How can I do it?

**Comment by jeremybmerrill** [comment]
Seems right that ` || line.hasOption('g')` should be present in https://github.com/tabulapdf/tabula-java/blob/master/src/main/java/technology/tabula/CommandLineApp.java#L255 -- the `-g` option should have `whichExtractionMethod` return `ExtractionMethod.DECIDE`, not `ExtractionMethod.DECIDE` (which is what it appears to do now, and what it appears to have (erroneously?) done for years). Am I missing something, @jazzido ?

**Comment by laigor** [comment]
> Seems right that `|| line.hasOption('g')` should be present in https://github.com/tabulapdf/tabula-java/blob/master/src/main/java/technology/tabula/CommandLineApp.java#L255 -- the `-g` option should have `whichExtractionMethod` return `ExtractionMethod.DECIDE`, not `ExtractionMethod.DECIDE` (which is what it appears to do now, and what it appears to have (erroneously?) done for years). Am I missing something, @jazzido ?
`ExtractionMethod.DECIDE`, not `ExtractionMethod.DECIDE` ? May be not `ExtractionMethod.BASIC`

**Comment by jeremybmerrill** [comment]
@laigor you're right; just a typo; fixed now.

**Comment by jazzido** [comment]
@jeremybmerrill should we just remove the `|| line.hasOption('g')` in that `if` so it defaults to `ExtractionMethod.DECIDE`?

**Comment by jeremybmerrill** [comment]
Yes

**Comment by laigor** [comment]
I made changes and compiled but unfortunately it still does not work:
```
java -jar tabula-1.0.3-jar-with-dependencies.jar -g example.pdf
"ПАО СБЕРБАНК Г. МОСКВА",,,БИК,044525225
"",,,Сч. No,30101810400000000225
"Банк получателя",,,,
"ИНН 7723889433 КПП",772401001,,Сч. No,40702810338250018579
"Общество с ограниченной ответственностью ""1001",,,,
"КРЕПЕЖ""",,,,
"Получатель",,,,
No,Код,"Товары (работы, услуги)",Кол-во,Ед.,Цена,Сумма без скидки,,Скидка(наценка),,Сумма
1,М0000127581,FBN II 8х71 /10/20 Клиновой,8 000,шт,"55,80","446 400,00",,"89 280,00",,"357 120,00"
"",,"анкер со шпилькой, гоц. сталь",,,,,,,,
"",,"(507575) fischer, (уп. 50 шт)",,,,,,,,
2,М0000127594,FBN II 10х86 /10/20 Клиновой,8 000,шт,"88,84","710 720,00",,"142 144,00",,"568 576,00"
"",,"анкер со шпилькой, гоц. сталь",,,,,,,,
"",,"(507579) fischer, (уп. 50 шт)",,,,,,,,
3,М0000127593,FBN II 10х86 /10/20 Клиновой,8 000,шт,"116,44","931 520,00",,"186 304,00",,"745 216,00"
"",,"анкер со шпилькой, нерж. сталь",,,,,,,,
"",,"А4 (507558) fischer, (уп. 50 шт)",,,,,,,,
4,М0000127580,FBN II 8х71 /10/20 Клиновой,8 000,шт,"82,34","658 720,00",,"131 744,00",,"526 976,00"
"",,"анкер со шпилькой, нерж. сталь",,,,,,,,
"",,"А4 (507555) fischer, (уп. 50 шт)",,,,,,,,
```

**Comment by jeremybmerrill** [comment]
The autodetect method is not magic; it only works perfectly on a subset of PDFs. For others, you'll have to give Tabula guidance about the location of a table or what method to use to extract it.

**Comment by laigor** [comment]
For my example.pdf web version of tabula correctly detect tables. What keys need to be used when starting tabula-java to show the coordinates of the found tables?
